config/routes.rb
Rails.application.routes.draw do

  root 'statics#index'

  controller :statics do
  get :home
  get :about
  get :services
  get :portfolio
  get :team
  get :contact, to: 'statics#contact'
  post 'contact', to:'statics#create'
end

get 'services/softdevelopment'
get 'services/devops'
get 'services/projectmanagement'
get 'services/qatesting'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	#validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :message, :phone, :companyname, :subject

 validates :name, 
 presence: true

 validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController


end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

 def index 
 end
 
 def about
 end

 def services
 end

 def portfolio

 end

 def team

 end

 def contact

 	@message=Contact.new
 end


 	def new
 		@message = Contact.new
	end

	def create
			@message = Contact.new(message_params)
			if (@message.valid? and @message.save)
				UserMailer.new_message(@message).deliver
				flash[:notice]="Your message has not been sent succesfully." 
				redirect_to contact_path
				else
				flash[:notice]="Your message has not been sent succesfully."
				puts "mess #{flash[:notice]}"
				redirect_to contact_path
 			end
 	end

 
 private

  def message_params
    params.require(:contact).permit(:name, :email, :phone, :companyname, :subject, :message)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer>
		<div class="footer">
			<div class="container">
				<div class="social-icon">
					<div class="col-md-4">
						<ul class="social-network">
							<li><a href="#" class="fb tool-tip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#" class="twitter tool-tip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#" class="gplus tool-tip" title="Google Plus"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="#" class="linkedin tool-tip" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
							<li><a href="#" class="ytube tool-tip" title="You Tube"><i class="fa fa-youtube-play"></i></a></li>
						</ul>	
					</div>
				</div>
				
				<div class="col-md-4 col-md-offset-4">
					<div class="copyright">
						&copy; OCTOBER  2016 by <a target="_blank" href="http://bootstraptaste.com/" title="Free Twitter Bootstrap WordPress Themes and HTML templates">ROCKET TESTTailor</a>. All Rights Reserved.
					</div>
                    <!-- 
                        All links in the footer should remain intact. 
                        Licenseing information is available at: http://bootstraptaste.com/license/
                        You can buy this theme without footer links online at: http://bootstraptaste.com/buy/?theme=Company
                    -->
				</div>						
			</div>
			
			<div class="pull-right">
				<a href="#home" class="scrollup"><i class="fa fa-angle-up fa-3x"></i></a>
			</div>		
		</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rocket-TESTTailor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<%= render 'layouts/header' %>	
	<%= yield %>	
<%= render 'layouts/footer'%>	

</body>
</html>

app/views/services/devops.html.erb
<br><br>
	<div id="breadcrumb">
		<div class="container">	
			<div class="breadcrumb">							
				<li><%=link_to 'Home',root_path,id:'link'%></a></li>
				<li>Services</li>			
			</div>		
		</div>	
	</div>

<div class="services">
		<div class="container">
			<h3>DevOps</h3>
			<hr>
			<div class="col-md-6">
				<img src="/assets/4.jpg" class="img-responsive">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque</p>
			</div>
			
			<div class="col-md-6">
				<div class="media">
					<ul>
						<li>
							<div class="media-left">
								<i class="fa fa-pencil"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">DevOPs</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget
							</div>
						</li>
						
					</ul>
				</div>
			</div>
		</div>
	</div>	
	
	<div class="sub-services">
		<div class="container">
			<div class="col-md-6">
				<div class="media">
					<ul>
						<li>
							<div class="media-left">
								<i class="fa fa-pencil"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Landing Page</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
						<li>
							<div class="media-left">
								<i class="fa fa-book"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Training</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
						<li>
							<div class="media-left">
								<i class="fa fa-rocket"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Logo Design</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
					</ul>
				</div>
			</div>
						
			<div class="col-md-6">
				<img src="assets/4.jpg" class="img-responsive">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque</p>
			</div>
		</div>
	</div>	

app/views/services/projectmanagement.html.erb
<br>
<br>
	<div id="breadcrumb">
		<div class="container">	
			<div class="breadcrumb">							
				<li><%=link_to 'Home',root_path,id:'link'%></a></li>
				<li>Services</li>			
			</div>		
		</div>	
	</div>

<div class="services">
		<div class="container">
			<h3>Project Management</h3>
			<hr>
			<div class="col-md-6">
				<img src="/assets/4.jpg" class="img-responsive">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque</p>
			</div>
			
			<div class="col-md-6">
				<div class="media">
					<ul>
						<div class="media-left">
								<i class="fa fa-tasks"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Project Management</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.
								Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.
								Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.
								Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>	
	
	<div class="sub-services">
		<div class="container">
			<div class="col-md-6">
				<div class="media">
					<ul>
						<li>
							<div class="media-left">
								<i class="fa fa-pencil"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Landing Page</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
						<li>
							<div class="media-left">
								<i class="fa fa-book"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Training</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
						<li>
							<div class="media-left">
								<i class="fa fa-rocket"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Logo Design</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
					</ul>
				</div>
			</div>
						
			<div class="col-md-6">
				<img src="/assets/4.jpg" class="img-responsive">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque</p>
			</div>
		</div>
	</div>	

app/views/services/qatesting.html.erb
<br>
<br>
	<div id="breadcrumb">
		<div class="container">	
			<div class="breadcrumb">							
				<li><%=link_to 'Home',root_path,id:'link'%></a></li>
				<li>Services</li>			
			</div>		
		</div>	
	</div>

<div class="services">
		<div class="container">
			<h3>QA Testing</h3>
			<hr>
			<div class="col-md-6">
				<img src="/assets/4.jpg" class="img-responsive">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque</p>
			</div>
			
			<div class="col-md-6">
				<div class="media">
					<ul>
						
							<div class="media-left">
								<i class="fa fa-book"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">QA Testing</h4>
								<p>As we understand the hurdles to be overcome in agile development and agile testing we're able to offer the best solutions.
								As we understand the hurdles to be overcome in agile development and agile testing we're able to offer the best solutions.
								As we understand the hurdles to be overcome in agile development and agile testing we're able to offer the best solutions.
								</p>
							</div>
						</li>
					
					</ul>
				</div>
			</div>
		</div>
	</div>	
	
	<div class="sub-services">
		<div class="container">
			<div class="col-md-6">
				<div class="media">
					<ul>
						<li>
							<div class="media-left">
								<i class="fa fa-pencil"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Landing Page</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
						<li>
							<div class="media-left">
								<i class="fa fa-book"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Training</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
						<li>
							<div class="media-left">
								<i class="fa fa-rocket"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Logo Design</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
					</ul>
				</div>
			</div>
						
			<div class="col-md-6">
				<img src="/assets/4.jpg" class="img-responsive">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque</p>
			</div>
		</div>
	</div>	

app/views/services/softdevelopment.html.erb
<br>
<br>
	<div id="breadcrumb">
		<div class="container">	
			<div class="breadcrumb">							
				<li><%=link_to 'Home',root_path,id:'link'%></a></li>
				<li>Services</li>			
			</div>		
		</div>	
	</div>

<div class="services">
		<div class="container">
			<h3>Software Development</h3>
			<hr>
			<div class="col-md-6">
				<img src="/assets/4.jpg" class="img-responsive">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque</p>
			</div>
			
			<div class="col-md-6">
				<div class="media">
					<ul>
						<li>
							<div class="media-left">
								<i class="fa fa-pencil"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Software Development</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.
								Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget
								Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget
								</p>
							</div>
						</li>
						
					</ul>
				</div>
			</div>
		</div>
	</div>	
	
	<div class="sub-services">
		<div class="container">
			<div class="col-md-6">
				<div class="media">
					<ul>
						<li>
							<div class="media-left">
								<i class="fa fa-pencil"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Landing Page</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
						<li>
							<div class="media-left">
								<i class="fa fa-book"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Training</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
						<li>
							<div class="media-left">
								<i class="fa fa-rocket"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Logo Design</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
					</ul>
				</div>
			</div>
						
			<div class="col-md-6">
				<img src="/assets/4.jpg" class="img-responsive">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque</p>
			</div>
		</div>
	</div>	

app/views/statics/about.html.erb
<br><br>
	<div id="breadcrumb">
		<div class="container">	
			<div class="breadcrumb">							
				<li><%=link_to 'Home',root_path,id:'link'%></a></li>
				<li>About Us</li>			
			</div>		
		</div>	
	</div>
<div class="dropup">
</div>
	<div class="aboutus">
		<div class="container">
			<h3>Our company information</h3>
			<hr>
			<div class="col-md-7 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
				<img src="assets/7.jpg" class="img-responsive">
				<h4>We Create, Design and Make it Real</h4>
				<p>Nam tempor velit sed turpis imperdiet vestibulum. In mattis leo ut sapien euismod id feugiat mauris euismod. 
				Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. 
				Phasellus id nulla risus, vel tincidunt turpis. Aliquam a nulla mi, placerat blandit eros. </p>
				<p>In neque lectus, lobortis a varius a, hendrerit eget dolor. Fusce scelerisque, sem ut viverra sollicitudin, est turpis blandit lacus,
				in pretium lectus sapien at est. 
				Integer pretium ipsum sit amet dui feugiat vitae dapibus odio eleifend.</p>
			</div>
			<div class="col-md-5 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
				<div class="skill">
					<h2>Our Skills</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>

					<div class="progress-wrap">
						<h3>Graphic Design</h3>
						<div class="progress">
						  <div class="progress-bar  color1" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 85%">
							<span class="bar-width">85%</span>
						  </div>

						</div>
					</div>

					<div class="progress-wrap">
						<h4>HTML</h4>
						<div class="progress">
						  <div class="progress-bar color2" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 95%">
						   <span class="bar-width">95%</span>
						  </div>
						</div>
					</div>

					<div class="progress-wrap">
						<h4>CSS</h4>
						<div class="progress">
						  <div class="progress-bar color3" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
							<span class="bar-width">80%</span>
						  </div>
						</div>
					</div>

					<div class="progress-wrap">
						<h4>Wordpress</h4>
						<div class="progress">
						  <div class="progress-bar color4" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 90%">
							<span class="bar-width">90%</span>
						  </div>
						</div>
					</div>
				</div>				
			</div>
		</div>
	</div>
	<div class="our-team">
		<div class="container">
			<h3>Our Team</h3>	
			<div class="text-center">
				<div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
					<img src="assets/services/1.jpg" alt="" >
					<h4>John Doe</h4>
					<p>Lorem ipsum dolor sit amet consectetur adipisicing eil sed deiusmod tempor</p>
				</div>
				<div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
					<img src="assets/services/2.jpg" alt="" >
					<h4>John Doe</h4>
					<p>Lorem ipsum dolor sit amet consectetur adipisicing eil sed deiusmod tempor</p>
				</div>
				<div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="900ms">
					<img src="assets/services/3.jpg" alt="" >
					<h4>John Doe</h4>
					<p>Lorem ipsum dolor sit amet consectetur adipisicing eil sed deiusmod tempor</p>
				</div>
			</div>
		</div>
	</div>
</html>

app/views/statics/services.html.erb
<br><br>
<div id="breadcrumb">
		<div class="container">	
			<div class="breadcrumb">							
				<li><%=link_to 'Home',root_path,id:'link'%></a></li>
				<li>Services</li>			
			</div>		
		</div>	
	</div>
	
	<div class="services">
		<div class="container">
			<h3>Company Services</h3>
			<hr>
			<div class="col-md-6">
				<img src="assets/4.jpg" class="img-responsive">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque</p>
			</div>
			
			<div class="col-md-6">
				<div class="media">
					<ul>
						<li>
							<div class="media-left">
								<i class="fa fa-pencil"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Software Development</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget...<%=link_to 'Read more',services_softdevelopment_path %></p>
							</div>
						</li>
						<li>
							<div class="media-left">
								<i class="fa fa-book"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">QA Testing</h4>
								<p>As we understand the hurdles to be overcome in agile development and agile testing we're able to offer the best solutions...<%=link_to 'Read more', services_qatesting_path %>
								</p>
							</div>
						</li>
						<li>
							<div class="media-left">
								<i class="fa fa-pencil"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">DevOps</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget...<%=link_to 'Read more',services_devops_path %></p>
							</div>
						</li>
						<li>
							<div class="media-left">
								<i class="fa fa-tasks"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Project Management</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget...<%=link_to 'Read more',services_projectmanagement_path %></p>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>	
	
	<div class="sub-services">
		<div class="container">
			<div class="col-md-6">
				<div class="media">
					<ul>
						<li>
							<div class="media-left">
								<i class="fa fa-pencil"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Landing Page</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
						<li>
							<div class="media-left">
								<i class="fa fa-book"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Training</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
						<li>
							<div class="media-left">
								<i class="fa fa-rocket"></i>						
							</div>
							<div class="media-body">
								<h4 class="media-heading">Logo Design</h4>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
								libero, pulvinar tincidunt leo consectetur eget.</p>
							</div>
						</li>
					</ul>
				</div>
			</div>
						
			<div class="col-md-6">
				<img src="assets/4.jpg" class="img-responsive">
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat 
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
				libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque</p>
			</div>
		</div>
	</div>